spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33306/test_r2dbc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: test_r2dbc
    password: test1!

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: kim.jungbin.springboot.domain
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse

logging:
  config: classpath:logback-spring.xml